#!/bin/bash

. SetGlobalSettings.sh
mkdir -p ${backupLocation}/dynamic
mkdir -p ${backupLocation}/static
cp ${WebLocationDynamic}/* ${backupLocation}/dynamic
cp ${WebLocationStatic}/* ${backupLocation}/static

